### ISSUE TITLE
Unresolved requirement: Import-Package: com.liferay.journal.service; version="[1.3.0,2.0.0)"

### ISSUE THREAD

**Issue by xhawk** [peerkar/liferay-gsearch#10]
Moi Petteri

I'm trying to deploy gsearch to Liferay CE 7.0.4 but I've stumbled into a problem with the core impl package. Is this a know issue? What could be wrong?
 
`⋊> ~/s/p/p/gsearch on master ⨯ blade sh install file:///Users/.../gsearch/fi.soveltia.liferay.gsearch.core.impl-2.1.1.jar
install file:///Users/.../gsearch/fi.soveltia.liferay.gsearch.core.impl-2.1.1.jar
Bundle ID: 515`

`⋊> ~/s/p/p/gsearch on master ⨯ blade sh start 515
start 515
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.core.impl [515]
  Unresolved requirement: Import-Package: com.liferay.journal.service; version="[1.3.0,2.0.0)"`

OSGi tells that 
`153|Active     |   10|Liferay Journal Service (3.17.3)`

**Comment by peerkar** [comment]
Terve,

There were some issues with CE 7.0.4 GA5.  Can you upgrade to 7.0.5 GA6? 
https://github.com/peerkar/liferay-gsearch/wiki/Compatibility-Matrix

**Comment by xhawk** [comment]
Thanks, didn't notice the compatibility matrix. I believe this resolves my issue.
