### ISSUE TITLE
Could not resolve module: com.liferay.portal.search.elasticsearch6.GSEARCH-PATCHED-IMPL

### ISSUE THREAD

**Issue by FriesBureau** [peerkar/liferay-gsearch#13]
Hi
I am running Liferay with Liferay Portal CE 7.1 GA2.

I have installed an Elasticsearch Server. Integrated the server with Liferay with the transport service.
Reindexing works. 
I created an asset publisher page with url: /viewasset
I inserted the GSearch portlet, but there are not results. 
"No search results. Please check spelling and try with more general keywords."
This is my modules log from: liferay/osgi/state/logs

org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.search.elasticsearch6.GSEARCH-PATCHED-IMPL [959]
  Unresolved requirement: Import-Package: com.liferay.portal.search.engine.adapter; version="[1.0.0,1.1.0)"

My database is Hypersonic. 

I request you to contact me at carstenfries@icloud.com, so we can arrange an agreement for you to guide me. Because I really need this GSearch to function on my Community Edition Liferay 7.1.

Best regards

Carsten Fries

**Comment by peerkar** [comment]
Hi @FriesBureau , there's an adapter for CE GA2 as well as new application binaries available. You can find the adapter here: https://github.com/peerkar/liferay-gsearch/tree/master/binaries/7.1/custom-elasticsearch-adapter/71-ce-ga2. Installation instructions in the distribution folder.
