### ISSUE TITLE
Possible to add extension points for overriding soy-templates?

### ISSUE THREAD

**Issue by deadcyclo** [peerkar/liferay-gsearch#14]
I don't have very much experience with soy-portlets (yet), but would it be possible for you to add osgi extension points for overriding soy-templates in the web-module to allow full customization of the rendering? If so that would be _highly_ useful and make this project super useful. (It already is a great project, but having to clone it to customize rendering makes it a bit more high maintenance to use).

**Comment by peerkar** [comment]
Hi,
Thanks for your feedback! I agree and that feature is actually close to the top on my task list. I'll let you know here when it's available.

**Comment by deadcyclo** [comment]
Awesome :+1: :+1: :+1:

**Comment by peerkar** [comment]
Thi @deadcyclo , I did some research on this and  I'm sorry to say but I didn't find a clean way to accomplish this - at least for now. OSGi fragments won't do here and Liferay SOY compiler doesn't understand SOY delegate package directives which could have been a possible approach (https://developers.google.com/closure/templates/docs/commands). I'm not too happy about this so I might take another look at the issue at later time but for now creating a fork and modifying the web-module is the way to go.

**Comment by FriesBureau** [comment]
I assumed that you wouldn't accomplish the task, because I understood the lack of comparatibilty between DXP and CE editions. Therefore I hired some expertise from Freelancer.com. Maybe the freelancer will create a fix for CE. Maybe not.

If I have a ready CE edition, I surely will send it to you. I love your work by the way, and would happily contribute. But I am not an expert in plugins.

Best regards

Carsten

**Comment by deadcyclo** [comment]
Thanks for your effort @peerkar I'll try to hint to Ray next time I talk to him about something that this is something we really need. Specially since it seems that LR is moving towards using Metal+soy internally (from my observation of recent changes in the source) this is going to be needed at some point. I'll keep you updated on any findings I do.
