### ISSUE TITLE
Could nor resolve module.

### ISSUE THREAD

**Issue by Rahul432013** [peerkar/liferay-gsearch#19]
Hi peerkar,
I am trying to make a sample web application using liferay making use of the code on the liferay documentaion site. the guestbook-web application. 
When I import the service builder built service and api in the module the application stops working.
when I go to the gogo shell and type lb it show the three applications are installed but are not active. when i enter the command start <ID>
It shows the errors that osgi is unable to resolve module com.docs.liferay.guestbook.service.
and so on.
Please let me know the reason why its happening, and help resolve the issue.

**Comment by peerkar** [comment]
Hi @Rahul432013,

When it comes to the issues you're having or any feedback on Liferay docs, if you have Liferay.com credentials and are logged in while on dev.liferay.com, there's a feedback link on the bottom of the page. Even better it is if you file an issue in Liferay JIRA at issues.liferay.com. There you can discuss and track the issues you're having. When filing issues, please pay a close attention on providing enough details about your environment, tool version's and how the guys can reproduce the issue. More explicit and clearer the description is, better changes the ticket has, to be taken into process. 

Also, you might want to discuss the problems on Liferay Community site. Again I'd say, more details you provide, faster you'll get tips and suggestions. There are very experienced Liferay consultants and community members hanging out there so you might be able to get help soon.

One more suggestion, in case you weren't not aware, you can access the complete Guestbook source code [here](https://github.com/liferay/liferay-docs/tree/7.1.x/develop/tutorials/code/com-liferay-docs-guestbook) so please have a look.

Thanks and I hope you're able to resolve the problems you're facing.

(As this is not a GSearch issue, I'll close it here.)
