### ISSUE TITLE
Allow facet on knowledgebase articles

### ISSUE THREAD

**Issue by denissignoretto** [peerkar/liferay-gsearch#3]
If I'm not wrong knowledge base articles are not fully supported. I've tryed adding the km model to the gsearch configuration (and included related labels on resource bundle file in core-impl module) but I get no results searching by everything neighter facteing by kb articles.
...
{
	"key": "knowledgebase",
	"entryClassName": "com.liferay.knowledgebase.model.KBArticle"
},
...

Thanks for any support to get it working with KB portlet too.

**Comment by peerkar** [comment]
Hi @denissignoretto. KB Portlet version 3.0.1 doesn't work in my DXP SP5 environment apparently because of newer kernel version. Which portal version are you running on?

**Comment by denissignoretto** [comment]
Hi peerkar, I've tested version 1.0.0 of gsearch it on Liferay CE GA5 7.0.4

**Comment by peerkar** [comment]
Hi @denissignoretto,

First, there's a typo in class name
{
"key": "knowledgebase",
"entryClassName": "com.liferay.knowledgebase.model.KBArticle"
},

That should be:
{
"key": "knowledgebase",
"entryClassName": "com.liferay.knowledge.base.model.KBArticle"
},

Second, I added the support for this class so you can just download new binaries (core-impl) and test.

**Comment by denissignoretto** [comment]
Hi @peerkar I've testd the new version and KB is now working! thank for supporting it!

**Comment by peerkar** [comment]
Glad it worked!
