### ISSUE TITLE
ES 6 adapter for DXP 7.0

### ISSUE THREAD

**Issue by peerkar** [peerkar/liferay-gsearch#9]
Create ES 6 adapter for DXP 7.0

**Comment by Joniteus** [comment]
Looking forward to this. I would like to use this in a project that we are starting.

**Comment by jverweijL** [comment]
Checkout https://web.liferay.com/marketplace/-/mp/application/106004266

**Comment by antoniobattista** [comment]
Is there a binary jar or a reposiroty for the adapter?

Thank you

**Comment by peerkar** [comment]
Hi, 

The custom adapter binaries, meant to be used with this application are with other binaries (by version) in https://github.com/peerkar/liferay-gsearch/tree/master/binaries. 

Only ES6 adapters are being updated and currently the 7.1 adapter only works up to DXP fixpack 2. The update for the newest 7.1  fixpack and for 7.0 SP8 will be provided in a few days.

The standard ES6 adapter, referenced by @jverweijL up cannot be used as such with this application without configuration changes, as it lacks some query translators etc.

The source for the adapter is in my liferay-portal fork and you can build it from there if needed. The current version 7.1 fixpack 2 is here: https://github.com/peerkar/liferay-portal/tree/gsearch-7.1.10-ga1-fp2/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl

**Comment by antoniobattista** [comment]
Thank you!!!!
We use Liferay 7.0 DXP. If you want and if you can push your source code we can help you to fix some bugs.

**Comment by ragogitpub** [comment]
Hello 

Without this issue fixed can this still be used with ES 6 ? What would be the drawbacks ?

**Comment by peerkar** [comment]
Adapter for 7.0 DXP, Service Pack 8 and 9 as well as fully backported application is now available at https://github.com/peerkar/liferay-gsearch/tree/master/binaries/7.0.

The adapter  doesn't work on CE-versions but it shouldn't be difficult to do the porting for those. Please see https://github.com/peerkar/liferay-portal/tree/gsearch-7.0.10-ga1-fp60/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl for the source code. Contributions welcome!

@antoniobattista : contributions are most welcome! Please ping me or please open a ticket on issue/module you'd like to contribute to. Thanks!
